mysql:
  host: "cubbie-database.cpt9nkl5ctfj.ap-southeast-1.rds.amazonaws.com"
  port: 3306
  username: "admin"
  password: "xtjx100$Z!X7uYjas7bfkh"
  database: "cubbie-database"

mssql:
  host: "localhost"
  port: 1433
  username: "sa"
  password: "Somesecure*password"
  database: "fk-migration-product"
  